server:
  port: 8086


spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm # The issuer URI for JWT is set to the Keycloak container's address.
          jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
    cors:
      allowed-origins: >
        http://localhost:2323 , 
        http://localhost:4200

  keycloak:
    url: http://localhost:8080/admin/realms/myrealm/users
    login-url: http://localhost:8080/realms/myrealm/protocol/openid-connect/token

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      linger.ms: 1
      batch.size: 16384
      properties:
        enable.idempotence: true
        allow.auto.create.topics: false
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: "com.holiday_tracker.shared_libraries.events.UserActivityEvent"
        spring.json.trusted.packages: "com.holiday_tracker.*"
      enable-auto-commit: false  # Ensures manual commit handling
      max-poll-records: 10  # Number of records per poll
      fetch-min-bytes: 1  # Minimum amount of data per fetchs
      fetch.wait.max.ms: 100  # Reduce fetch wait time


  kong:
    admin-url: http://localhost:8001

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    kafka: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
  default-produces-media-type: application/json
  paths-to-match: /**
  cache:
    disabled: true